sudo: false
dist: trusty
language: python
python:
  - '3.6'

before_install:
  - pip install -U pip awscli
  - aws configure set region $AWS_REGION
  - aws configure set preview.cloudfront true

install:
  - mkdir dist/ && cp -a assets/ index.html dist/

# ensure dist/ exists, meaning site was copied
script: test -d dist/

deploy:
  # deploy release to s3 bucket
  #
  # use script instead of s3 b/c the "s3" provider doesn't allow "delete"
  # functionality
  - provider: script
    script: aws --region "${AWS_REGION}" s3 sync --delete --acl private ./dist/ "s3://${S3_BUCKET}/${S3_PREFIX}/"
    skip_cleanup: true
    on:
      branch: release

after_deploy:
  - aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" --paths '/*'
